### ISSUE TITLE
Update lang to html tag

### ISSUE THREAD

**Issue by goulet-coder** [goulet-coder/goulet-coder.github.io#16]
Since the website is currently only written in English, we should add lang=en to the HTML tags to help search engines discover my website. 

[W3 Schools Tutorial](https://www.w3schools.com/tags/ref_language_codes.asp#:~:text=The%20HTML%20lang%20attribute%20can%20be%20used%20to,inside%20the%20%3Chtml%3E%20tag%2C%20like%20this%3A%20%3Chtml%20lang%3D%22en%22%3E.)

This is the feature that I am referencing.

**Comment by karinisantanna** [comment]
Hi, i do this!
