### ISSUE TITLE
Change Function name in JS file

### ISSUE THREAD

**Issue by goulet-coder** [goulet-coder/goulet-coder.github.io#18]
Current implementation of the dynamic navigation bar uses a JavaScript function called myFunction(), which is not very intuitive. It needs a better name. 
![image](https://user-images.githubusercontent.com/51882550/94983262-319db700-050f-11eb-8e4b-69b5030501f6.png)

Found in template.js file

**Comment by rounaksarda** [comment]
Hey! I can help you on this.

**Comment by rounaksarda** [comment]
> Hey! I can help you on this. As the function is changing the classname of the element with id "navigation" we can give the function name as change_Nav_Class() or class_Name_Change(), which is more appealing .

If you like it then assign me this issue.

**Comment by sreejithvs333** [comment]
Hi, please add the topic "hacktoberfest". I am participating in it. Please see https://hacktoberfest.digitalocean.com/hacktoberfest-update.

**Comment by goulet-coder** [comment]
> Hi, please add the topic "hacktoberfest". I am participating in it. Please see https://hacktoberfest.digitalocean.com/hacktoberfest-update.

Hello! I believe that I have added the hacktoberfest topic, but please let me know if the topic still doesn't appear.

Also, your work looks great!

**Comment by goulet-coder** [comment]
Small issue: need to update the name of the function where I use them (in my navigational bar)

**Comment by goulet-coder** [comment]
I resolved it.
